//400
export const CODE_BAD_REQUEST = "ERROR-BR-000";
export const CODE_INVALID_PASSWORD = "ERROR-BR-001";
export const CODE_INVALID_TOKEN = "ERROR-BR-002";
//401
export const CODE_UNAUTHORIZED_ERROR = "ERROR-UA-000";
export const CODE_EXPIRED_TOKEN = "ERROR-UA-001";
//403
export const CODE_FORBIDDEN = "ERROR-FB-000";
export const CODE_REFRESH_TOKEN_EXPIRED = "ERROR-FB-001";
//404
export const CODE_NOT_FOUND = "ERROR-NF-000";
export const CODE_USER_NOT_FOUND = "ERROR-NF-001";
export const CODE_PRODUCT_NOT_FOUND = "ERROR-NF-002";
export const CODE_CATEGORY_NOT_FOUND = "ERROR-NF-003";
export const CODE_HASH_TAG_NOT_FOUND = "ERROR-NF-004";
export const CODE_EVENT_NOT_FOUND = "ERROR-NF-005";
export const CODE_SEASON_NOT_FOUND = "ERROR-NF-006";
export const CODE_RECOMMAND_NOT_FOUND = "ERROR-NF-007";
//409
export const CODE_CONFLICT = "ERROR-CF-000";
export const CODE_DUPLICTED_USER = "ERROR-CF-001";
export const CODE_DUPLICTED_USER_NAME = "ERROR-CF-002";
export const CODE_DUPLICTED_USER_EMAIL = "ERROR-CF-003";
export const CODE_DUPLICTED_USER_NICKNAME = "ERROR-CF-004";
export const CODE_DUPLICTED_PRODUCT_NAME = "ERROR-CF-005";
export const CODE_DUPLICTED_CATEGORY_NAME = "ERROR-CF-006";
export const CODE_DUPLICTED_EVENT_NAME = "ERROR-CF-007";
export const CODE_DUPLICTED_SEASON_NAME = "ERROR-CF-008";
export const CODE_DUPLICTED_HASHTAG_NAME = "ERROR-CF-009";
export const CODE_DUPLICTED_RECOMMEND_NAME = "ERROR-CF-010";
//500
export const CODE_INTERNAL_SERVER_ERROR = "ERROR-ISE-000";
