
import Header from '@/components/layouts/Header'
import ChunsikList from '@/components/widgets/ChunsikList'
import MainBanner from '@/components/widgets/MainBanner'
import RecommandMdList from '@/components/widgets/RecommandMdList'
import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [ rcmd, setRcmd ] = useState<RecommendInfo>();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainBanner />
      <RecommandMdList key={key}/>
      <ChunsikList />
    </>
  )
}
