import HeaderBottom from '@/components/layouts/HeaderBottom'
import HeaderSub from '@/components/layouts/HeaderSub'
import HeaderTop from '@/components/layouts/HeaderTop'
import ChunsikList from '@/components/widgets/ChunsikList'
import MainBanner from '@/components/widgets/MainBanner'
import RecommandMdList from '@/components/widgets/RecommandMdList'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderTop/>
      <HeaderBottom />
      <MainBanner />
      <RecommandMdList />
      <ChunsikList />
    </>
  )
}
