import { RequestSubCategoryList } from "@/Service/CategoryService/CategoryService";
import { RequestProduct } from "@/Service/ProductService/ProductService";
import { getSeasonInfo } from "@/Service/SeasonService/SeasonService";
import { ProductInfo } from "@/Types/Product/Request";
import {
  FilterParams,
  MenuDataType,
  filterDataType,
} from "@/Types/filter/filterTypes";
import { headerMenu } from "@/Types/starbucksTypes";
import CategoryMenuList from "@/components/page/store/CategoryMenuList";
import PriceFilterList from "@/components/page/store/PriceFilterList";
import SeasonFilterList from "@/components/page/store/SeasonFilterList";
import SizeFilterList from "@/components/page/store/SizeFilterList";
import SubCategoryList from "@/components/page/store/SubCategoryList";
import ProductCard from "@/components/ui/ProductCard";
import Config from "@/configs/config.export";
import { REQUEST_PRODUCT } from "@/constants/Apis/URL";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { ChangeEventHandler, SetStateAction, useEffect, useState } from "react";

export default function Store() {
  const baseUrl = Config().baseUrl;
  const router = useRouter();

  const [pageNo, setPageNo] = useState<number>(0);
  const [order, setOrder] = useState<string>("product.id,DESC");

  const { pathname, query } = useRouter();
  const [category, setCategory] = useState(1);
  const [subCategory, setSubCategory] = useState(0);
  const [filterParams, setFilterParams] = useState<FilterParams>();
  const [priceRange, setPriceRange] = useState({
    startValue: 0,
    endValue: 0,
  });
  const [products, setProducts] = useState<ProductInfo[]>([]);

  const [filterMenuData, setFilterMenuData] = useState<MenuDataType[]>([]);
  const [sizeFilterData, setSizeFilterData] = useState<MenuDataType[]>([]);
  const [subFilterMenuData, setSubFilterMenuData] = useState<MenuDataType[]>(
    []
  );
  const [seasonMenuData, setSeasonMenuData] = useState<MenuDataType[]>([]);

  const [filterData, setFilterDatas] = useState<filterDataType[]>([]);

  const fetchSeasonData = () => {
    getSeasonInfo()
      .then((res) => {
        setSeasonMenuData([...res.data.seasonInfo]);
      })
      .catch((ex) => {
        console.log(ex);
      });
  };

  // useEffect(() => {
  //   if (filterData.length > 0) {
  //     console.log("필터링데이터", filterData);
  //     let queryUrl = "";
  //     filterData.forEach((item) => {
  //       queryUrl += `&${item.key}=${item.id}`;
  //     });
  //     router.push(`/store?category=${router.query.category}${queryUrl}`);
  //   }
  //   // console.log(menuList);
  // }, [filterData]);

  useEffect(() => {
    fetchSeasonData();
    setFilterMenuData([
      {
        id: 1,
        name: "전체",
        key: "category",
      },
    ]);
    RequestSubCategoryList(1).then((res) => {
      let myData: MenuDataType[] = [];
      res.data.subCategories.forEach((item: headerMenu) => {
        myData.push({
          id: item.id,
          name: item.name,
          key: "category",
        });
      });
      setFilterMenuData((filterMenuData) => [...filterMenuData, ...myData]);
    });
    setCategory(1);
  }, []);

  useEffect(() => {
    if (
      query.category &&
      query.category !== "1" &&
      typeof query.category === "string"
    ) {
      const subCategory: string = query.category;
      RequestSubCategoryList(parseInt(query.category)).then((res) => {
        console.log(res.data);
        let myData: MenuDataType[] = [];
        res.data.subCategories.forEach((item: headerMenu) => {
          myData.push({
            id: item.id,
            name: item.name,
            key: "subCategory",
          });
        });

        if (res.data.sizeInfo !== undefined) {
          console.log(res.data.sizeInfo);
          setSizeFilterData([...res.data.sizeInfo]);
        } else {
          setSizeFilterData([]);
        }
        setSubFilterMenuData(myData);
        setSubCategory(parseInt(subCategory));
      });
    } else if (query.category === "1") {
      setSubFilterMenuData([]);
    }
  }, [query]);

  useEffect(() => {
    console.log(router.asPath);
    let param = router.asPath + "&page=0&sort=product.id,DESC";
    param = param.slice(7, param.length);
    console.log(REQUEST_PRODUCT + param);

    RequestProduct(param).then((res) => {
      console.log(res.data.content);
      setProducts([...res.data.content]);
    });
  }, [router.query]);

  const handleOnChangeSelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const value = e.target.value;
    setOrder(value);
  };

  return (
    <>
      <Head>
        <title>상품 조회</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          margin: "50px 0 0 0",
        }}
      >
        <CategoryMenuList setCategory={setCategory} data={filterMenuData} />
        {sizeFilterData.length > 0 && <SizeFilterList data={sizeFilterData} />}
        <PriceFilterList setPriceRange={setPriceRange} />
        {subFilterMenuData.length > 0 && (
          <SubCategoryList category={category} data={subFilterMenuData} />
        )}
        <SeasonFilterList data={seasonMenuData} />
      </div>
      <div className="searchResultContent">
        <div className="searchResult-filter" id="search-result-filter">
          <img src="/assets/images/icons/reload.png" />
          <button>
            <p>체리블라썸</p>
            <img className="close-icon" src="/assets/images/icons/close.png" />
          </button>
          <button>
            <p>1만원대</p>
            <img className="close-icon" src="/assets/images/icons/close.png" />
          </button>
        </div>
        <div className="content-order">
          <select id="xyz" onChange={handleOnChangeSelect}>
            <option value={"product.id,DESC"}>신상품순</option>
            <option value={"product.price,ASC"}>낮은가격순</option>
            <option value={"product.price,DESC"}>높은가격순</option>
          </select>
        </div>
        <section className="searchResultProduct">
          <div className="product-container">
            {products &&
              products.map((element, idx) => (
                <ProductCard
                  key={"product " + element.id + idx}
                  productId={element.id}
                  imageSrc={element.thumbnail}
                  productTitle={element.name}
                  productPrice={`${element.price}`}
                />
              ))}
          </div>
        </section>
      </div>
    </>
  );
}
